// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import {console} from "forge-std/console.sol";
import {Script} from "forge-std/Script.sol";
import {CurtaPCTF2023Audio} from "src/utils/CurtaPCTF2023Audio.sol";

/// @notice A script to print the audio sound values generated by
// `CurtaPCTF2023Audio` for  testing purposes.
contract P is Script {
    /// @notice Prints the sound values for a range of time ticks in the audio.
    /// @dev Set `START_TICK` and `END_TICK` to specify the token ID to print.
    function run() public view {
        uint256 START_TICK = 35937;
        uint256 END_TICK = 35969;
        for (uint256 i = START_TICK; i < END_TICK; ++i) {
            uint256 v = CurtaPCTF2023Audio.getSoundValueAtSample(i);
            console.log(v);
        }
    }
}
